name: ci-workflow

on:
  [push, workflow_dispatch]

jobs:

  build:
    name: Build and Package
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a Start script line
        run: echo Start api-spec Build

      - name: Set up adoptopenjdk8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'gradle'
      
      - name: Build with Gradle
        run: ./gradlew build            
