name: ci-workflow

on:
  push:
    branches: 
      - main 
      - develop
      - 'support-*'

 # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:  

jobs:

  build:
    name: Build and Package
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v2       